### PR TITLE
Add paths_changed events

### PR DESCRIPTION
**Pull request by Takachi67**
Add the paths_changed event to emits in polygon.js

### CODE REVIEW

**Comment by NathanAP** [comment]
Hello! Thanks for your PR!

Did you solve your problem with polygons with this change or is there something else you're doing?
Just confirm it for me, then I'll accept this ASAP

**Comment by Takachi67** [comment]
Hello,

It's not a bug, it's just annoying to have a Vue warn saying "Extraneous non-emits event listeners (paths_changed) were passed to component but could not be automatically inherited because component renders fragment or text root nodes.".

Thanks ! 👯

**Comment by NathanAP** [comment]
OK! I'll send as a fix anyway. This will be part of `0.3.1`. I'll update tomorrow morning (about 15-16 hours from now) into npm :)

**Review by NathanAP — APPROVED** [review]

**Comment by NathanAP** [comment]
Its up! Thanks again

**Pull request merged**
