### PR TITLE
Ability to customize input in autocomplete

### PR DESCRIPTION
**Pull request by websitevirtuoso**

### CODE REVIEW

**Comment by websitevirtuoso** [comment]
@NathanAP 
You need to configure repo to check some syntax etc etc
Like in fawmi repo

**Comment by NathanAP** [comment]
I'll look on how to do it and the best options as soon as I can!

**Comment by websitevirtuoso** [comment]
I tried to use something like
<slot>
 <!--  fallback input --!>
 <input />
</slot>

But in this case, I can't access $refs.input. Maybe you will find something more flexible

**Comment by NathanAP** [comment]
> @NathanAP You need to configure repo to check some syntax etc etc Like in fawmi repo

I enabled it now :) It is using the same configs Fawmi used before. Let me know if there is something else to do in Dependabot.

**Comment by NathanAP** [comment]
Yeah I'm figuring it out about the documentation website. Never used netlify before. I'll remove that link for now.

**Comment by websitevirtuoso** [comment]
You can merge them

**Pull request merged**
